### ISSUE TITLE
Exclude `logback.xml` from final Jar?

### ISSUE THREAD

**Issue by corrspt** [siahsang/red-utils#3]
Hey

Thanks for the work on the library, it's helping us out. 
We've found an issue, and would like to request to remove the 'logback.xml' file from the library. It appears that it overrides the local application's configuration.

[Exclude Logback](https://mkyong.com/maven/maven-exclude-logback-xml-in-jar-file/) this seems to be a away to do it.

Thanks.

**Comment by mdcarreira** [comment]
I created [this PR](https://github.com/siahsang/red-utils/pull/5) to fix this issue.

**Comment by siahsang** [comment]
Thank you, done.
